require('./environment')
require('./babel')
require('./log')
if(!process.argv[2] || process.argv[2] === 'api') require('./api/server')
if(!process.argv[2] || process.argv[2] === 'web') require('./website/app')